server:
  port: 8080

spring:
  profiles:
    include: ovsx
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: openvsx
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never

  security:
      oauth2:
        client:
          registration:
            eclipse:
              authorization-grant-type: authorization_code
              redirect-uri: http://localhost/login/oauth2/code/eclipse
              scope: openvsx_publisher_agreement, profile
          provider:
            eclipse:
              authorization-uri: https://accounts.eclipse.org/oauth2/authorize
              token-uri: https://accounts.eclipse.org/oauth2/token
              user-info-uri: https://accounts.eclipse.org/oauth2/UserInfo
              user-name-attribute: name
              user-info-authentication-method: header

management:
  health:
    probes:
      enabled: true

ovsx:
  databasesearch:
    enabled: true
  elasticsearch:
    enabled: false
  eclipse:
    base-url: https://api.eclipse.org
    publisher-agreement:
      timezone: US/Eastern
